version: '3'
services:
  chatbot:
    build:
      context: ../ # 指定dockerfile文件的所在路径  
      dockerfile: Dockerfile
    image: 22405925chatbot.azurecr.io/chatbot
    command: python main.py
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:5.7
    container_name: mysql
    command:
      [
        #使用 command 可以覆盖容器启动后默认执行的命令
        '--character-set-server=utf8mb4', #设置数据库表的数据集
        '--collation-server=utf8mb4_unicode_ci'
      ]
    restart: always
    environment:
      MYSQL_DATABASE: telegram_chatbot
      MYSQL_ROOT_PASSWORD: wangkai2933
    ports:
      - 33307:3306
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
